# Generated by Django 6.1.1 on 2026-09-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('org_id', models.CharField(max_length=32)),
                ('location_name', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SourceEntry',
            fields=[
                ('entry_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('record_ref_raw', models.CharField(blank=True, max_length=64)),
                ('record_ref_normalized', models.CharField(blank=True, db_index=True, max_length=32)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('recorded_on', models.DateField(blank=True, null=True)),
                ('recorded_on_raw', models.CharField(blank=True, max_length=32)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('value_raw', models.CharField(blank=True, max_length=64)),
                ('label', models.CharField(blank=True, max_length=255)),
                ('raw_row', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='SourceRecord',
            fields=[
                ('record_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('location_id', models.CharField(blank=True, max_length=64)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('event_date_raw', models.CharField(blank=True, max_length=32)),
                ('category_code', models.CharField(blank=True, max_length=32)),
                ('actor_id', models.CharField(blank=True, max_length=32)),
                ('base_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adjustment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_value_raw', models.CharField(blank=True, max_length=64)),
                ('state', models.CharField(blank=True, max_length=32)),
                ('raw_row', models.JSONField(default=dict)),
            ],
        ),
    ]
